### ISSUE TITLE
modules pré requis à diocumenter

### ISSUE THREAD

**Issue by empierre** [k20human/domoticz-veolia-eau#1]
sudo apt-get install python3 python3-xlrd

**Comment by k20human** [comment]
J'ai rajouté des informations dans le README qui était un peu (beaucoup) pauvre
Voir le commit https://github.com/k20human/domoticz-veolia-eau/commit/107d8eea9c5343fea4bc463a43ab5e498bbf0f72

**Comment by empierre** [comment]
merci !

Je fais un peu la même chose pour Linky: https://github.com/empierre/domoticz_linky

**Comment by k20human** [comment]
J'avais moi aussi mis le même système en place pour le Linky (https://github.com/k20human/domoticz-linky) mais ma méthode n'est pas fiable car l'API d'Enedis n'est pas fiable et donc mes données sont erronées ... (car il ne s'agit pas d'un compteur comme pour Veolia)

Ta méthode utilise la base de données interne de Domoticz donc ça m'a l'air bien mieux :)

De mon côté je suis en train de voir avec une solution proposée par mon fournisseur d'énergie car je préfère passer par l'API de Domoticz
