### ISSUE TITLE
Nouveau site en ile de france

### ISSUE THREAD

**Issue by slallemand** [k20human/domoticz-veolia-eau#6]
Bonjour,

le site veolia pour l'ile de france a changé (je ne sais pas si c'est le cas des autres régions).
Le site et les urls ont changé et donc la récupération des informations ne fonctionnent plus.

J'essaie de trouver mais pour le moment je sèche un peu.

**Comment by k20human** [comment]
Bonjour,

Je viens de me connecter sur mon espace client, le site est identique à un avant sur mon compte. Je suis en Idf (Eau de PVM). La récupération de mon côté dans Domoticz fonctionne donc toujours normalement.

**Comment by BornTKill** [comment]
Bonsoir,

Marche plus depuis 8j dans le 94100
Et le nouveau site ne fourni rien.

Je continue de chercher.

**Comment by thiklop** [comment]
Je confirme, j'ai le même problème dans le 92140.

**Comment by k20human** [comment]
Le mieux est d'utiliser le debugguer de Chrome ou Firefox pour voir les requêtes qui sont lancées et récupérer les bonnes URL avec les bons paramètres.

Pour le moment de mon côté c'est à priori l'ancien site donc je ne peux malheureusement pas avoir les modifs :(

**Comment by Warp95** [comment]
Bonjour,
Pour moi aussi les URL du script ne sont plus bonne. 
URL du script : https://www.service.eau.veolia.fr/home.html
URL vers le nouveau site : https://www.vedif.eau.veolia.fr

![Capture](https://user-images.githubusercontent.com/13014428/54073617-d56aa680-4289-11e9-8783-e0b20b430320.PNG)

**Comment by k20human** [comment]
Mon compte est toujours sur l'ancien site, impossible de me connecter sur https://www.vedif.eau.veolia.fr.

La migration doit se faire petit à petit.
Je suis en congés pendant 1 semaine je peux regarder à mon retour pour la connexion mais sans compte ça va être difficile d'aller plus loin malheureusement.

Si quelqu'un qui a la compétence peut le faire et créer une branche dédiée je la mergerai vers mon repo

**Comment by Warp95** [comment]
J'ai bien essayé, mais ces nouvelles pages web me semblent vraiment au dessus de mes compétences.
Ils ont vraiment changé leurs mode de développement.

Je peux te donner mon compte le temps que tu puisses y jeter un œil si tu veux.
Cdt,
Eric

**Comment by k20human** [comment]
En effet un login / mdp m'aiderait pour développer le système

**Comment by Warp95** [comment]
Comment faite pour rendre notre communication privé, pour le login / pwd ?

Le mar. 12 mars 2019 à 18:37, Kévin Mathieu <notifications@github.com> a
écrit :

> En effet un login / mdp m'aiderait pour développer le système
>

**Comment by k20human** [comment]
Tu peux m'envoyer les identifiants sur kmat AT gmail DOT com

**Comment by Warp95** [comment]
Bonjour Kévin,

Cette adresse semble ne pas exister ! (.fr) peut-être ?

Eric

Le sam. 16 mars 2019 à 15:26, Kévin Mathieu <notifications@github.com> a
écrit :

**Comment by k20human** [comment]
Je me suis trompé en postant le commentaire, j'ai édité juste après mais la notification a dû partir avant ...

kmat.null AT gmail DOT com

**Comment by k20human** [comment]
Bon ...
J'ai un peu galéré car ils utilisent un framework JS pour gérer le site (Aurora) et c'est galère.

J'ai donc dû utilisé Selenium. Sur mon poste de DEV (Ubuntu 18.10) ça fonctionne, en théorie ça devrait fonctionner avec la procédure que j'ai mis sur le README sur un Raspberry 3.

J'ai créé une branche sépcifique pour ce site, ça serait bien si quelqu'un pouvait la tester :)
https://github.com/k20human/domoticz-veolia-eau/tree/site/idf

**Comment by BornTKill** [comment]
Hello. Je test et te dit ça.
Merci pour le boulot !

**Comment by BornTKill** [comment]
Re,

Pour le moment en headless ca marche pas trop.

python3.5 execute.py 
Traceback (most recent call last):
  File "execute.py", line 116, in <module>
    browser = webdriver.Firefox(firefox_profile=profile, firefox_options=options)
  File "/usr/local/opt/python-3.5.6/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/opt/python-3.5.6/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/opt/python-3.5.6/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/opt/python-3.5.6/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/opt/python-3.5.6/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

root@raspberrypi:/home/pi/domoticz-veolia-eau/domoticz-veolia-eau# cat geckodriver.log 
1553331176537	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.b520tf9u2OxN"
**Error: GDK_BACKEND does not match available displays**

Du coup je lance avec xvfb-run. J'ai ceci :

root@raspberrypi:/home/pi/domoticz-veolia-eau/domoticz-veolia-eau# xvfb-run python3.5 execute.py
Traceback (most recent call last):
  File "execute.py", line 116, in <module>
    browser = webdriver.Firefox(firefox_profile=profile, firefox_options=options)
  File "/usr/local/opt/python-3.5.6/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/opt/python-3.5.6/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/opt/python-3.5.6/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/opt/python-3.5.6/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/opt/python-3.5.6/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

Ca va plus loin d'après le log :

root@raspberrypi:/home/pi/domoticz-veolia-eau/domoticz-veolia-eau# cat geckodriver.log 
1553331239552	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.ELcHiJz3iitF"

(firefox-esr:2235): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox-esr:2235): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox-esr:2235): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox-esr:2235): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
1553331245196	Marionette	INFO	Listening on port 2828

(/usr/lib/firefox-esr/firefox-esr:2318): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox-esr/firefox-esr:2318): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox-esr/firefox-esr:2318): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox-esr/firefox-esr:2318): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

###!!! [Child][MessageChannel] Error: (msgtype=0x3E0003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv


###!!! [Child][MessageChannel] Error: (msgtype=0x3E0003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv

[GFX1-]: Receive IPC close with reason=AbnormalShutdown
[Child 2318] WARNING: pipe error (3): Connexion r?-initialis?e par le correspondant: file /build/firefox-esr-Dv9pMn/firefox-esr-52.9.0esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322
[Child 2318] ###!!! ABORT: Aborting on channel error.: file /build/firefox-esr-Dv9pMn/firefox-esr-52.9.0esr/ipc/glue/MessageChannel.cpp, line 2152
[Child 2318] ###!!! ABORT: Aborting on channel error.: file /build/firefox-esr-Dv9pMn/firefox-esr-52.9.0esr/ipc/glue/MessageChannel.cpp, line 2152

**Comment by Warp95** [comment]
Bon pas mieux de mon coté.

1. Sur mon Raspbian Jessie, pour les l'install j'ai été obligé de forcer le python3 comme ceci : 

sudo apt-get install **python3 python3-pip** xvfb iceweasel
sudo **pip3** install selenium
wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-arm7hf.tar.gz && tar xzf geckodriver-v0.23.0-arm7hf.tar.gz && sudo mv geckodriver /usr/local/bin && rm geckodriver-v0.23.0-arm7hf.tar.gz
git clone -b site/idf https://github.com/k20human/domoticz-veolia-eau.git

2. Ce qui donne ca : 

pi@raspberrypi:~/scripts/domoticz-veolia-eau $ python3 execute.py               Traceback (most recent call last):
  File "execute.py", line 116, in <module>
    browser = webdriver.Firefox(firefox_profile=profile, firefox_options=options)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 135, in request_encode_body
    **urlopen_kw)
TypeError: urlopen() got multiple values for keyword argument 'body'

**Comment by k20human** [comment]
J'essaye de debugguer ça ce WE.
Pour info mon Rasp 3 est sous Strech.

**Comment by k20human** [comment]
Bon ...

Voici ce que j'ai essayé sans succès :

- Exécuter la commande `/usr/bin/Xvfb :99 -ac -screen 0 1024x768x8 & export DISPLAY=":99"`
- Avec Firefox ESR 52.9.0 et geckodriver-v0.17.0-arm7hf : ça tourne mais il ne trouve pas la balise de l'email, surement parce que FF n'arrive pas à interpréter correctement le JS (avec les versions supéreiru ça ne fonctionne pas car incompatible)
- Avec Firefox ESR 60.6.1 (https://packages.debian.org/fr/stretch/firefox-esr) et le driver 0.17 à 0.23 : erreur comme @BornTKill 

Je sèche un peu là ... Il faudrait pouvoir tester avec une autre version de Firefox intermédiaire mais impossible d'en trouver une pour Raspbian arm ...

**Comment by Zoylamb** [comment]
J'ai rencontré les mêmes problèmes.
Après avoir tester shadowJS (non fonctionnel), je m'en suis sorti en utilisant plutôt chromedriver ([lien](https://github.com/electron/electron/releases/download/v1.6.0/chromedriver-v2.21-linux-armv7l.zip)) avec  selenium.

J'utilise aussi pyvirtualdisplay pour la partie masquage display
J'ai modifié le script aussi pour n'avoir que la dernière valeur du fichier.

Je met en pièce jointe le script si l'auteur veut l'utiliser
[execute.py.txt](https://github.com/k20human/domoticz-veolia-eau/files/3193053/execute.py.txt)

Merci à l'auteur.

**Comment by BornTKill** [comment]
Bonjour.

Merci pour cette contribution @Zoylamb Toutefois j’ai un parse error :

root@raspberrypi:/home/pi/domoticz-veolia-eau# python3.5 execute.py
  File "execute.py", line 172
    row = list(csv.reader(f, delimiter=';')))[-1]
                                            ^
SyntaxError: invalid syntax

**Comment by Zoylamb** [comment]
Il y a une parenthèse en trop dans la ligne

`
row = list(csv.reader(f, delimiter=';'))[-1]

`

**Comment by k20human** [comment]
J’intégrerai tout ça à la branche quand j'aurai un peu de temps

**Comment by Warp95** [comment]
Bonjour Kévin,

Avez vous intégré le code à la branche ?

Cordialement
Eric

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le ven. 24 mai 2019 à 09:38, Kévin Mathieu <notifications@github.com> a
écrit :

> J’intégrerai tout ça à la branche quand j'aurai un peu de temps
>

**Comment by k20human** [comment]
Non désolé toujours pas eu le temps de m'y pencher ...

**Comment by Warp95** [comment]
Bonjour Kévin,

Toujours pas  ?
Cordialement
Eric

Le lun. 3 juin 2019 à 07:37, Kévin Mathieu <notifications@github.com> a
écrit :

> Non désolé toujours pas eu le temps de m'y pencher ...
>

**Comment by s0nik42** [comment]
Bonjour,

Justement, je suis entrain de faire une evolution du script que je souhaitais partager ici.
 
J'ai rajouté :
- La gestion dynamique des timers
- La gestion de plusieurs contrats (dans mon cas j'en ai 2)
- un mode debug activant la visualisation graphique de la navigation bien utile
- Des valeurs par defauts pour le config.json

Je m'attaque à la partie chargement des données dans domoticz et je dois dire que je suis assez surpris par les limitations que je rencontre. 

J'ai creer un Virtual Sensor Counter que j'ai configuré en "Water" apparaissant en tant que "RFX Meter" est bien ce que vous utilisez aussi ?

Ensuite le script de K20Human à ce jour envoie uniquement la derniere consommation journaliere qu'il trouve dans le fichier et la pousse dans domoticz via les APIs.

Mes questions : 
- Le script initial pousse le nombre de litres journalier, pourtant je comprend de la doc de domoticz qu'il faut lui envoyer la "valeur absolue" du compteur. Est-ce volontaire ?
- Peut-on charger l'historique dans dates anterieures en poussant également une date ou alors faudrait-il plutot creer un vrai plugin comme le plugin Linky ? 
- Veolia ne fournissant le relevé que qq jours apres la conso, comment reconcilier les volumes remontés avec les bonnes dates dans domoticz ?

Merci,
Julien

**Comment by k20human** [comment]
@Warp95 j'avais complètement zappé ce sujet.
Je viens d'intégrer les modifs de @Zoylamb dans la branche site/idf (https://github.com/k20human/domoticz-veolia-eau/tree/site/idf). Je n'ai pas testé du tout. De plus mon compte est toujours sur l'ancien site de Volia Eau (PVM).

@s0nik42 oui c'est bien ce type de compteur que j'utilise pour ma part.
Actuellement le script récupère le fichier Excel avec l'ensemble des consommations des derniers mois, ça prend la dernière ligne et ça récupère l'index du compteur, donc bien la "valeur absolue" et non pas juste l'incrémentation

Malheureusement l'API de Domoticz ne permet pas de charger l'historique, il faut pour cela passer par la manipulation de la base de données. Un plugin Domoticz permet de le faire plus facilement comme le plugin Linky (https://github.com/guillaumezin/DomoticzLinky/blob/master/plugin.py)

En effet Veolia fourni la données 1 à 3j après la consommation réelle. Cela occasionne un décalage dans les dates donc. De mon côté ce n'est pas gênant car mon but était d'avoir ma consommation globale et vérifier qu'il n'y a pas de surconsommation. Si on veut les vrais dates il faut passer par un plugin et la manipulation de la base.

Si quelqu'un veut transformer ce script en véritable plugin qu'il n'hésite pas, malheureusement je n'ai plus trop le temps de faire du dev perso ces temps ci ...

**Comment by s0nik42** [comment]
@k20human Oui merci on est aligné, je me suis rapproché du développeur de domoticzLinky pour savoir comment il chargeait les infos dans la DB, car a la lecture de son code et de la doc de Domoticz, je ne suis pas sur que cela soit une solution pérenne. 

Wait and See.

Julien

**Comment by s0nik42** [comment]
Hello k20human, 

J'ai mené ma petite enquête et j'ai réussi à trouver une solution à l'ensemble des éléments précédents et j'ai réussi à charger les données aux bonnes dates. 
Y a donc l'historique et le compteur à jour.

Finalement j'ai refait tout le script. Je t'ai rajouté dans les credits 🥇 

J'ai crée un repository pour cela ici : https://github.com/s0nik42/veolia-idf/

Encore merci,

Julien

**Comment by BornTKill** [comment]
Bonjour.

Merci à tous pour vos contributions. Je teste ça sous peu et vous fais un retour.

Bonne journée à tous.

**Comment by Warp95** [comment]
Bonjour Julien,

Je bute sur : ImportError: No module named 'pyvirtualdisplay'.
Même apres avoir installé 'pyvirtualdisplay' : sudo pip install
pyvirtualdisplay

Pouvez-vous nous donner les prérequis a l'exécution de votre script ?

Cordialement,
Eric

**Comment by s0nik42** [comment]
Salut Warp95,
 
C'est du python3, je pense que tu as du installer le module en python2.XX 
il faut utiliser la commande pip3 et non pip. je t'invite à poser tes questions sur le repo Veolia-idf s'il concerne ce script comme ca les autres en profiteront :)

Tiens moi au courant si ca marche.

julien

**Comment by k20human** [comment]
@s0nik42 très beau boulot !
Je suis allé voir le script, bien mieux que ce que j'a fait.

Si je comprend bien il est possible dé gérer l'historique de Domoticz via l'API JSON en passant le `svalue` d'un certaine manière ?

**Comment by s0nik42** [comment]
Merci ^_^, 
Tout a fait, il faut passer par un autre type de compteur : "Managed Counter" qui accepte qu'on lui passe une date en meme temps qu'une valeur.

**Comment by tirso58** [comment]
Bonjour, j'ai voulue essayer cette méthode avec Firefox et Geckodriver mais j'ai fini par renoncer car cette installation a consommé tout mon espace disque (4+3Gb). Disproportionné par rapport à ce qu'il pourrait apporter.

**Comment by s0nik42** [comment]
Bonsoir @tirso58,  il y a un bug qq part je pense. Le script ne stocke aucun donnée. Quel est le repertoire qui fait 7GiB ?

**Comment by tirso58** [comment]
Bonjour @s0nik42 et merci pour votre réponse. Ce qui est en cause n'est pas le script lui même mais tous les prérequis. J'ai Chromium mais pas Firefox sur mon Rasp. J'ai voulu installer l'ensemble des prérequis et là, j'ai eu un rep. de 3Go sur /opt et environ 4Go pour Firefox/Geckodriver. Cela a rempli complétement mon disque j'ai tout désinstallé.
Je verrai plus tard si d'autres évolutions arrivent.
Merci

**Comment by k20human** [comment]
Je n'ai pas prévu de faire évoluer le script qui répond toujours à mes besoins (qui sont assez basiques ...)
Par contre je suis étonné que Geckodriver prenne autant de place !

Je clôture ce ticket étant donné que le problème d'origine est résolu depuis longtemps

**Comment by s0nik42** [comment]
@tirso58 je rejoins Kévin, la taille utilisée est vraiment importante, quel repertoire prenait de la place ? la prochaine fois vous devriez installer depuis les packages et non depuis les sources. la place utilisée dans /opt devrait etre d'a peine qq dizaine de mega

**Comment by tirso58** [comment]
s0nik42 et k20human merci pour vos réponses. Clairement je ne maitrise pas les sujets mais j'ai réussi à installer un Raspberry avec Domoticz et pas mal d'autres choses. Maintenant pour le script en cause, il implique beaucoup de prérequis et n'ayant visiblement pas trouvé les bons emplacements ou les bonnes versions, j'ai explosé mon espace disque. Évidemment vous n'êtes pas en cause mais vu qu'il n'y a pas de procédures d'install (ou je ne les ai pas trouvé) je suis passé par une install qui est disproportionnée .
Voici ce que j'ai installé:
sudo apt install firefox-esr
sudo apt install -y --reinstall gcc-arm-linux-gnueabihf libc6-armhf-cross libc6-dev-armhf-cross
mkdir -p /opt
cd /opt
sudo git clone https://github.com/s0nik42/veolia-idf
cd veolia-idf
sudo git pull
sudo chmod ugo+x veolia-idf-domoticz.py
pip3 install -r requirements.txt
